version: '3.1'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_sequelize
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
